version: '2'
services:
    swhome-app:
        image: swhome
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://swhome-postgresql:5432/swhome
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    swhome-postgresql:
        extends:
            file: postgresql.yml
            service: swhome-postgresql
