version: '2'
services:
    swhome-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/swhome/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=swhome
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
